CREATE TABLE CUSTOMER (
    ID SERIAL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    BIRTHDATE VARCHAR(255)
);

insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Hassan', 'Husted', '2000-01-01');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Rosario', 'Raye', '2000-02-02');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Carrie', 'Cappello', '2000-03-03');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Azucena', 'Agnew', '2000-04-04');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Benito', 'Browning', '2000-05-05');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Peggy', 'Pam', '2000-06-06');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Contessa', 'Cobian', '2000-07-07');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Erick', 'Edge', '2000-08-08');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Osvaldo', 'Oquendo', '2000-09-09');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Jennell', 'Jump', '2000-10-10');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Leandro', 'Lueck', '2000-11-11');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Ma', 'Motsinger', '2000-12-12');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Rachael', 'Rachal', '2001-01-01');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Zimmerman', 'Zachary', '2001-02-02');
insert into CUSTOMER (FIRSTNAME, LASTNAME, BIRTHDATE) VALUES ('Zimmerman', 'Aaron', '2001-03-03');

CREATE TABLE NEW_CUSTOMER (
                          ID SERIAL,
                          FIRSTNAME VARCHAR(255) NOT NULL,
                          LASTNAME VARCHAR(255) NOT NULL,
                          BIRTHDATE VARCHAR(255)
);